language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq xvfb
  - sudo apt-get install -qq firefox
install:
  - pip install -U pip
  - pip install pytest
  - pip install .
before_script:
  - git clone https://github.com/federico123579/Trading212-API.git
  - cd Trading212-API
  - ls -l
script:
  - py.test -v test.py
after_success:
  - coveralls
group: stable
dist: precise
os: linux
